# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt update
    sudo apt install g++-arm-linux-gnueabihf
    wget http://archive.raspberrypi.org/debian/pool/main/w/wiringpi/wiringpi_2.50_armhf.deb
    sudo dpkg --add-architecture armhf
    sudo dpkg -i wiringpi_2.50_armhf.deb --force

  displayName: 'Setup'

- script: |
    arm-linux-gnueabihf-g++ -lwiringpi main.cpp -o main
  displayName: 'Build'
